# Generated by Django 2.0 on 2020-02-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
