# Generated by Django 2.1.5 on 2020-08-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.CharField(choices=[('Leadership', 'Leadership')], default='Leadership', max_length=70, null=True),
        ),
    ]
