# Generated by Django 2.1.4 on 2020-04-13 12:47

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_name', models.CharField(max_length=80)),
                ('Module_duration', models.CharField(max_length=191)),
                ('module_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_number', models.CharField(max_length=80)),
                ('Unit_name', models.CharField(max_length=191)),
                ('unit_duration', models.CharField(max_length=191)),
                ('Month', models.CharField(max_length=80)),
                ('unit_description', models.TextField()),
                ('Modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ecommerce_app.Modules')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Delivery',
            field=models.CharField(default=django.utils.timezone.now, max_length=191),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Validation',
            field=models.CharField(default=django.utils.timezone.now, max_length=191),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ecommerce_app.Product'),
        ),
    ]
