# Generated by Django 2.0 on 2020-02-01 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='registrar.Course'),
            preserve_default=False,
        ),
    ]
