# Generated by Django 2.1.4 on 2020-04-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20200413_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='ecommerce_app.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Delivery',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='Modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='ecommerce_app.Modules'),
        ),
    ]
