# Generated by Django 2.0 on 2020-02-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20200201_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='course',
        ),
    ]
