# Generated by Django 2.0 on 2020-02-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20200206_2053'),
        ('ecommerce_app', '0003_remove_product_course'),
    ]

    operations = [
    ]
