# Generated by Django 2.1.4 on 2020-04-13 21:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_auto_20200413_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Course_module_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
