# Generated by Django 2.1.4 on 2020-04-13 23:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_product_course_module_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Validator_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='Validator_name',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
