# Generated by Django 2.1.4 on 2020-04-13 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_auto_20200413_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Validator_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=191),
            preserve_default=False,
        ),
    ]
