# Generated by Django 2.1.4 on 2020-04-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_auto_20200413_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Validation',
        ),
    ]
