# Generated by Django 2.1.5 on 2020-07-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_shortcourse_shortcourselecture_shortcoursemodules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcourselecture',
            name='shortcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcourselectures', to='ecommerce_app.ShortCourse'),
        ),
    ]
