# Generated by Django 2.1.5 on 2020-08-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_auto_20200726_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='units',
            name='Modules',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
