# Generated by Django 2.1.4 on 2020-01-27 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='coursediscussionthread',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='coursefinalmark',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='coursesetting',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='coursesubmission',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
    ]
