# Generated by Django 2.0 on 2020-02-02 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course'),
        ),
        migrations.AddField(
            model_name='purchase_course',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
