# Generated by Django 2.1.5 on 2020-07-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_auto_20200726_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
