# Generated by Django 2.1.5 on 2020-07-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_auto_20200730_0112'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
    ]
