# Generated by Django 2.1.5 on 2020-08-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_auto_20200730_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
