# Generated by Django 2.1.5 on 2020-08-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0008_course_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quick_Overview',
            fields=[
                ('quickoverview_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='', max_length=60, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course')),
            ],
            options={
                'db_table': 'at_quickoverview',
            },
        ),
    ]
