# Generated by Django 2.1.5 on 2020-08-09 00:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0009_quick_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quickview',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
