# Generated by Django 2.1.5 on 2020-08-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0011_auto_20200809_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='quickview',
        ),
    ]
