# Generated by Django 2.1.5 on 2020-08-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0012_remove_course_quickview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quick_overview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickoverview', to='registrar.Course'),
        ),
    ]
