# Generated by Django 2.1.4 on 2020-01-27 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landpagetoppickcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course', to_field='id'),
        ),
    ]
