# Generated by Django 2.1.4 on 2020-03-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landpage', '0001_initial'),
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landpagetoppickcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.Course'),
        ),
    ]
