# Generated by Django 2.1.5 on 2020-08-25 12:22

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0002_landpagetoppickcourse_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(db_index=True, max_length=100)),
                ('brief_description', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('blog_story', models.TextField(blank=True)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blogcategory',
                'verbose_name_plural': 'blogcategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('brief_description', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('brief_story', models.TextField(blank=True)),
                ('location', models.CharField(db_index=True, max_length=100, null=True)),
                ('venue', models.CharField(db_index=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('End_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eventcategory',
                'verbose_name_plural': 'eventcategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mediacategory',
                'verbose_name_plural': 'mediacategories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='media',
            name='mediacategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='landpage.MediaCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='landpage.EventCategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='landpage.BlogCategory'),
        ),
        migrations.AlterIndexTogether(
            name='media',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='event',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='blog',
            index_together={('id', 'slug')},
        ),
    ]
